defmodule SymphonyElixir.PromptBuilder do
  @moduledoc """
  Builds agent prompts from Linear issue data.
  """

  alias SymphonyElixir.{Config, Workflow}

  @render_opts [strict_variables: true, strict_filters: true]

  @spec build_prompt(SymphonyElixir.Linear.Issue.t(), keyword()) :: String.t()
  def build_prompt(issue, opts \\ []) do
    template =
      Workflow.current()
      |> prompt_template!()
      |> parse_template!()

    template
    |> Solid.render!(
      %{
        "attempt" => Keyword.get(opts, :attempt),
        "issue" => issue |> Map.from_struct() |> to_solid_map()
      },
      @render_opts
    )
    |> IO.iodata_to_binary()
  end

  @spec build_planning_prompt(SymphonyElixir.Linear.Issue.t(), keyword()) :: String.t()
  def build_planning_prompt(issue, _opts \\ []) do
    """
    You are the planning phase for Linear ticket #{issue.identifier}.

    Issue context:
    Identifier: #{issue.identifier}
    Title: #{issue.title}
    Current status: #{issue.state}
    Labels: #{inspect(issue.labels)}
    URL: #{issue.url}

    Description:
    #{issue.description || "No description provided."}

    Your job is to create a detailed execution plan, NOT to implement anything.

    Steps:
    1. Read the repo's CLAUDE.md for project-specific guidance
    2. Explore relevant code paths for the task
    3. Write a structured execution plan
    4. Append the plan to this Linear issue's description using the Linear MCP tools
    5. Do NOT create branches, write code, or make commits

    IMPORTANT: You are ONLY planning. Do not implement, commit, or push any changes.

    Append the following structured plan to the issue description (do not overwrite existing content).

    IMPORTANT: Write acceptance criteria that capture BOTH behavioral intent AND implementation
    approach. The behavioral description ensures design intent survives into execution. The
    implementation detail gives the executor a head start on where to look and what to change.
    Always include a concrete test scenario with specific inputs and expected outputs.

    ---
    ## Execution Plan (generated by Opus)

    ### Design Intent
    [1-2 sentences: WHY this change matters. What should the user or system experience differently
    after this is done? This helps the executor make judgment calls when the spec is ambiguous.]

    ### Task Type
    [feature / bug fix / refactor / research]

    ### Approach
    [2-3 sentences on the strategy — enough for the executor to understand the direction,
    not a step-by-step implementation guide]

    ### Acceptance Criteria
    Each criterion captures behavioral intent, implementation approach, and a test scenario.

    - [ ] Behavior: When [trigger/condition], [expected outcome].
          Implementation: [which files/functions to modify, what the change looks like].
          Test: [concrete scenario with specific inputs → expected outputs — e.g., "given a company contacted 15 days ago, the role should be skipped and a log entry should explain why"]
    - [ ] [Additional criteria — prefer fewer, precise criteria over many vague ones]

    ### Risks / Ambiguities
    - [anything unclear that the executor should watch for — flag design decisions that need judgment]
    """
  end

  @spec build_execution_continuation_prompt(integer(), integer()) :: String.t()
  def build_execution_continuation_prompt(turn_number, max_turns) do
    """
    The planning phase (Opus) has completed and appended an execution plan to the issue description.

    Read the updated issue description to find the execution plan under "## Execution Plan (generated by Opus)", then execute it.

    Continuation guidance:

    - This is execution turn ##{turn_number} of #{max_turns} for the current agent run.
    - The Opus planning turn explored the repo and wrote a structured plan — follow it.
    - Resume from the current workspace and workpad state instead of restarting from scratch.
    - The original task instructions and prior turn context are already present in this thread, so do not restate them before acting.
    - Focus on the remaining ticket work and do not end the turn while the issue stays active unless you are truly blocked.
    """
  end

  defp prompt_template!({:ok, %{prompt_template: prompt}}), do: default_prompt(prompt)

  defp prompt_template!({:error, reason}) do
    raise RuntimeError, "workflow_unavailable: #{inspect(reason)}"
  end

  defp parse_template!(prompt) when is_binary(prompt) do
    Solid.parse!(prompt)
  rescue
    error ->
      reraise %RuntimeError{
                message: "template_parse_error: #{Exception.message(error)} template=#{inspect(prompt)}"
              },
              __STACKTRACE__
  end

  defp to_solid_map(map) when is_map(map) do
    Map.new(map, fn {key, value} -> {to_string(key), to_solid_value(value)} end)
  end

  defp to_solid_value(%DateTime{} = value), do: DateTime.to_iso8601(value)
  defp to_solid_value(%NaiveDateTime{} = value), do: NaiveDateTime.to_iso8601(value)
  defp to_solid_value(%Date{} = value), do: Date.to_iso8601(value)
  defp to_solid_value(%Time{} = value), do: Time.to_iso8601(value)
  defp to_solid_value(%_{} = value), do: value |> Map.from_struct() |> to_solid_map()
  defp to_solid_value(value) when is_map(value), do: to_solid_map(value)
  defp to_solid_value(value) when is_list(value), do: Enum.map(value, &to_solid_value/1)
  defp to_solid_value(value), do: value

  defp default_prompt(prompt) when is_binary(prompt) do
    if String.trim(prompt) == "" do
      Config.workflow_prompt()
    else
      prompt
    end
  end
end
