defmodule SymphonyElixir.TwoPhaseExecutionTest do
  use SymphonyElixir.TestSupport

  # -- Schema: new Claude config fields --

  describe "schema parses new claude fields" do
    test "planning_model is nil by default" do
      assert {:ok, settings} = Config.settings()
      assert is_nil(settings.claude.planning_model)
    end

    test "planning_model can be set" do
      write_workflow_file!(Workflow.workflow_file_path(), claude_planning_model: "opus")
      assert {:ok, settings} = Config.settings()
      assert settings.claude.planning_model == "opus"
    end

    test "execution_model is nil by default" do
      assert {:ok, settings} = Config.settings()
      assert is_nil(settings.claude.execution_model)
    end

    test "execution_model can be set" do
      write_workflow_file!(Workflow.workflow_file_path(), claude_execution_model: "sonnet")
      assert {:ok, settings} = Config.settings()
      assert settings.claude.execution_model == "sonnet"
    end

    test "upgrade_model defaults to opus" do
      assert {:ok, settings} = Config.settings()
      assert settings.claude.upgrade_model == "opus"
    end

    test "upgrade_model can be overridden" do
      write_workflow_file!(Workflow.workflow_file_path(), claude_upgrade_model: "sonnet")
      assert {:ok, settings} = Config.settings()
      assert settings.claude.upgrade_model == "sonnet"
    end

    test "upgrade_labels defaults to empty" do
      assert {:ok, settings} = Config.settings()
      assert settings.claude.upgrade_labels == []
    end

    test "upgrade_labels can be set" do
      write_workflow_file!(Workflow.workflow_file_path(), claude_upgrade_labels: ["opus", "complex"])
      assert {:ok, settings} = Config.settings()
      assert settings.claude.upgrade_labels == ["opus", "complex"]
    end

    test "upgrade_priorities defaults to empty" do
      assert {:ok, settings} = Config.settings()
      assert settings.claude.upgrade_priorities == []
    end

    test "upgrade_priorities can be set" do
      write_workflow_file!(Workflow.workflow_file_path(), claude_upgrade_priorities: [1, 2])
      assert {:ok, settings} = Config.settings()
      assert settings.claude.upgrade_priorities == [1, 2]
    end
  end

  # -- PromptBuilder: planning and execution continuation prompts --

  describe "PromptBuilder.build_planning_prompt/2" do
    test "includes issue context" do
      issue = %Issue{
        id: "test-1",
        identifier: "TEST-1",
        title: "Add feature X",
        description: "Implement the thing",
        state: "Todo",
        labels: ["backend"],
        url: "https://linear.app/test/TEST-1"
      }

      prompt = PromptBuilder.build_planning_prompt(issue)

      assert prompt =~ "TEST-1"
      assert prompt =~ "Add feature X"
      assert prompt =~ "Implement the thing"
      assert prompt =~ "Todo"
      assert prompt =~ "backend"
    end

    test "includes structured plan format" do
      issue = %Issue{
        id: "test-2",
        identifier: "TEST-2",
        title: "Fix bug",
        state: "In Progress",
        labels: [],
        url: "https://linear.app/test/TEST-2"
      }

      prompt = PromptBuilder.build_planning_prompt(issue)

      assert prompt =~ "## Execution Plan (generated by Opus)"
      assert prompt =~ "### Design Intent"
      assert prompt =~ "### Task Type"
      assert prompt =~ "### Approach"
      assert prompt =~ "### Acceptance Criteria"
      assert prompt =~ "### Risks / Ambiguities"
    end

    test "instructs agent NOT to implement" do
      issue = %Issue{
        id: "test-3",
        identifier: "TEST-3",
        title: "Plan only",
        state: "Todo",
        labels: [],
        url: "https://linear.app/test/TEST-3"
      }

      prompt = PromptBuilder.build_planning_prompt(issue)

      assert prompt =~ "ONLY planning"
      assert prompt =~ "Do not implement"
      assert prompt =~ "Do NOT create branches"
    end

    test "handles nil description" do
      issue = %Issue{
        id: "test-4",
        identifier: "TEST-4",
        title: "No desc",
        description: nil,
        state: "Todo",
        labels: [],
        url: "https://linear.app/test/TEST-4"
      }

      prompt = PromptBuilder.build_planning_prompt(issue)
      assert prompt =~ "No description provided."
    end
  end

  describe "PromptBuilder.build_execution_continuation_prompt/2" do
    test "references execution plan" do
      prompt = PromptBuilder.build_execution_continuation_prompt(2, 20)

      assert prompt =~ "planning phase (Opus) has completed"
      assert prompt =~ "Execution Plan (generated by Opus)"
    end

    test "includes turn numbers" do
      prompt = PromptBuilder.build_execution_continuation_prompt(3, 10)

      assert prompt =~ "execution turn #3 of 10"
    end

    test "instructs to follow the plan" do
      prompt = PromptBuilder.build_execution_continuation_prompt(2, 20)

      assert prompt =~ "follow it"
      assert prompt =~ "Resume from the current workspace"
    end
  end

  # -- Backward compatibility --

  describe "backward compatibility" do
    test "config without new fields works identically" do
      # Default workflow file has no planning/upgrade fields
      assert {:ok, settings} = Config.settings()
      assert settings.claude.model == "sonnet"
      assert is_nil(settings.claude.planning_model)
      assert is_nil(settings.claude.execution_model)
      assert settings.claude.upgrade_labels == []
      assert settings.claude.upgrade_priorities == []
    end

    test "build_prompt still works with template variables" do
      write_workflow_file!(Workflow.workflow_file_path(),
        prompt: "Work on {{ issue.identifier }}: {{ issue.title }}"
      )

      issue = %Issue{
        id: "compat-1",
        identifier: "COMPAT-1",
        title: "Normal issue",
        description: "Regular work",
        state: "In Progress",
        labels: [],
        url: "https://linear.app/test/COMPAT-1"
      }

      prompt = PromptBuilder.build_prompt(issue)
      assert prompt =~ "COMPAT-1"
      assert prompt =~ "Normal issue"
    end
  end
end
